// Shared question bank — ported from the prototype. Server and client both
// import from here so the maker's and guesser's views always match.

const RAW=[
"A perfect Friday night?|Takeout and the couch|Out with friends|Cooking together|Asleep by 9",
"Pick a superpower|Flying|Invisibility|Reading minds|Teleporting",
"Zombie apocalypse: you are the...|Leader|Scavenger|Lone wolf|First to go",
"When annoyed, you text with...|Total silence|Sarcasm|A long paragraph|A single thumbs-up",
"Dream trip|Beach|Big city|Mountains|Road trip",
"Mornings are...|Up before the alarm|Snooze x5|Coffee, no talking|A myth",
"Go-to comfort food|Pizza|Pasta|Ice cream|Soup",
"Pineapple on pizza?|Yes, always|Never|Only if dared|Depends who is watching",
"Worst chore|Dishes|Laundry|Bathroom|Taking out the trash",
"Karaoke energy|Power ballad|Rap verse|Pop banger|Absolutely not singing",
"Cat or dog?|Dog|Cat|Both|Neither",
"A lazy Sunday|Movie marathon|Long walk|Nap|Brunch out",
"Biggest fear|Spiders|Heights|Public speaking|Being forgotten",
"Ideal date|Fancy dinner|Mini golf|Picnic|Staying in",
"You would rather win|The lottery|A dream job|Perfect health|Endless free travel",
"Coffee order|Black|Sweet and milky|Iced|Tea, actually",
"Phone habit|Doomscrolling|Group chats|Games|Rarely on it",
"Social battery drains after...|One hour|Half a day|A weekend|Never",
"Best season|Spring|Summer|Autumn|Winter",
"Text reply speed|Instant|Within the hour|Whenever|Days later",
"A surprise day off, you...|Sleep|Run errands|Go on an adventure|Do nothing",
"Movie genre|Comedy|Horror|Romance|Sci-fi",
"Shower time|Morning|Night|Both|Whenever",
"Best gift|A handwritten note|An experience|Something useful|Surprise snacks",
"At a party you are...|The life of it|By the snacks|In a deep kitchen chat|Already gone",
"Biggest pet peeve|Loud chewing|Lateness|Slow walkers|Unanswered texts",
"Decade to live in|70s|80s|90s|2000s",
"You could never give up|Music|Sweets|Sleep|Your phone",
"Road trip role|Driver|DJ|Navigator|Snack manager",
"Planning style|Spreadsheet|Rough idea|Wing it|Someone else plans",
"Favorite meal|Breakfast|Lunch|Dinner|Midnight snack",
"In an argument|Talk it out|Cool off first|Get loud|Avoid it",
"Money goes to...|Food|Clothes|Gadgets|Experiences",
"Rainy day means|Cozy day in|Long drive|Dancing in it|Bad mood",
"Exercise style|Gym|Running|Yoga|Walking counts",
"Bedroom temperature|Freezing|Cool|Warm|Blanket burrito always",
"Reality show you would join|Cooking|Survival|Dating|Home makeover",
"Superstition|Knock on wood|Lucky item|Horoscopes|None",
"Pizza night|Delivery|Homemade|Frozen is fine|Fancy pizzeria",
"Snack drawer|Chips|Chocolate|Fruit|Cereal from the box",
"New hobby|Painting|Gaming|Hiking|Baking",
"Cringe you still remember|A school talent show|An old text|A bad haircut|A wrong name",
"Favorite holiday|Birthday|Christmas|Summer break|New Year's",
"Weekend alarm|Never|Same as weekdays|Only for plans|Panic at noon",
"Money mindset|Saver|Spender|Investor|Winging it",
"Dinner is at 10pm, you are...|Fine|Starving|Cooking|Already ate",
"Comfort watch|Sitcom|Cartoon|Reality TV|Documentary",
"Ideal home|City flat|Cabin|Beach house|Big garden",
"Birthday plans|Big party|Small dinner|Trip away|Ignore it",
"Text to a crush|A meme|A long message|A voice note|Nothing",
"You could eat forever|Cheese|Chocolate|Bread|Sushi",
"Bad day fix|A hug|Food|Alone time|Distraction",
"First to apologize|Me|Them|Whoever is wrong|Nobody, we move on",
"Alternate career|Musician|Chef|Explorer|Author",
"A spider appears|Scream|Cup and paper|Leave it|Call for help",
"Favorite way to relax|Music|A bath|A book|Video games",
"Movie theater snack|Popcorn|Candy|Nachos|Nothing",
"Night owl or early bird|Night owl|Early bird|Depends|Both, badly",
"Favorite weather|Sun|Snow|Storm|Fog",
"You laugh hardest at|Memes|Stand-up|Friends|Someone falling over",
"Best way to spend a call|Dinner on video|Watching together|A long talk|Silent company",
"Missing them, you...|Look at old photos|Send a voice note|Make a playlist|Keep busy",
"Time zones: you would...|Stay up late|Wake up early|Schedule it|Wing it",
"First thing at a reunion|A huge hug|Food|Sleep|Talk for hours",
"Perfect care package|Snacks|A letter|A hoodie|A playlist",
"Goodnight message|A call|A text|A voice note|Just an emoji",
"Who visits first|Me|Them|Meet halfway|Take turns",
"Long-distance rule|Daily call|Never miss goodnight|Space is fine|Weekly plans",
"First kiss spot|A rainy street|A party|A car|At home",
"Flirting style|Teasing|Compliments|Eye contact|Terrible puns",
"Jealousy|Never|A little|I hide it|I tell all",
"Pet name|Cute|Silly|Classic|None",
"Dancing together|Slow|Fast|In the kitchen|Never",
"Cuddle position|Big spoon|Little spoon|Face to face|Own side",
"Date outfit|Dress up|Comfy|Matching|Whatever is clean",
"Saying I love you|Often|Rarely|In writing|At random",
"Childhood dream job|Astronaut|Doctor|Athlete|Artist",
"Favorite kid snack|Cereal|Candy|Fruit snacks|Sandwiches",
"As a kid you were...|The loud one|The quiet one|The troublemaker|The teacher's pet",
"Childhood favorite|Stuffed animal|Lego|Video games|A bike",
"Saturday mornings|Cartoons|Outside all day|Sleeping in|Helping in the kitchen",
"Childhood fear|The dark|Monsters|Dogs|Getting lost",
"Best school subject|Math|Art|Gym|Lunch",
"Sleepover activity|Movies|Truth or dare|Video games|Pillow fort",
"At family gatherings you...|Cook|Clean up|Tell stories|Hide with the kids",
"Family tradition you love|The big meal|Gifts|Music|Games",
"Funniest at family dinner|Me|A parent|A sibling|A cousin",
"Family road trips|Are we there yet|Sleeping|Snacks|Singing",
"Family group chat role|Memes|Photos|Reminders|Muted",
"Best cook in the family|Me|A parent|A grandparent|Takeout",
"Family game night|Board games|Cards|Charades|Arguments",
"You take after...|A parent|A grandparent|A sibling|Nobody",
"In the group you are the...|Planner|Comedian|Listener|Snack provider",
"Friend night out|Dinner|A bar|A movie|Game night",
"What you send friends|Memes|Voice notes|Long rants|Food photos",
"After a fight with a friend|Talk soon|Need space|Send a meme|Wait for them",
"Best friend talent|Making you laugh|Advice|Cooking|Driving",
"Group trip|Beach|City|Camping|Theme park",
"You would trust a friend with...|A secret|Your keys|Your pet|Your playlist",
"Time with friends|Weekly|Monthly|Rarely but deep|Always",
"Breakfast pick|Pancakes|Eggs|Cereal|Skip it",
"Favorite cuisine|Italian|Mexican|Asian|Indian",
"Dessert|Cake|Ice cream|Cookies|Not a dessert person",
"Cooking skill|Chef level|Decent|Toast only|Delivery expert",
"Spice level|Mild|Medium|Hot|Painful",
"Window or aisle|Window|Aisle|Middle, honestly|Whichever is free",
"Packing style|Days early|Night before|Minutes before|Forgets something",
"Vacation vibe|Do nothing|Sightsee|Eat everything|Adventure sports",
"Hotel or rental|Hotel|Rental|Camping|A friend's couch",
"Trip souvenir|Magnet|T-shirt|Snacks|Photos only",
"Anniversary plan|Fancy dinner|Home-cooked meal|A trip|Just us at home",
"Love language|Words|Time together|Gifts|Touch",
"Meeting the parents|Confident|Nervous|Over-prepared|Avoid it",
"Date night pick|Movie|Dinner|A walk|Game night",
"Sweetest gesture|Breakfast in bed|A surprise note|A planned day|Remembering a detail",
"Stranded on an island with...|Music|Books|Snacks|A boat",
"Lottery win, first buy|A house|A trip|A car|Give it away",
"Alien invasion, you...|Hide|Negotiate|Fight|Take photos",
"Most likely to...|Get lost|Be late|Cry at a movie|Win an argument",
"Worst superpower|Talking to plants|Instant sneezing|Freezing time for 1s|Smelling everything",
"Morning routine|Shower first|Coffee first|Phone first|Rush out",
"The fridge is...|Full|Sad and empty|All leftovers|Just condiments",
"Music while working|Pop|Lo-fi|Silence|A podcast",
"Show binge|One episode|Three|A whole season|Falls asleep",
"Tidy or messy|Tidy|Organized mess|Messy|Depends on mood",
"Cartoons growing up|The classics|90s|2000s|Whatever was on",
"Lunchbox item|Sandwich|Snacks|Fruit|Whatever was left",
"Birthday as a kid|A party|Cake only|Family dinner|A surprise trip",
"Best friend habit|Late replies|Overplanning|Always hungry|Random calls",
"Group chat status|Most active|Reads, never replies|Sends memes|Muted",
"Friend's karaoke pick|A ballad|Rap|Pop|Never sings",
"Friend adventure|Road trip|Concert|Hike|Food crawl",
"Family recipe|Grandma's dish|Dad's grill|Mom's soup|Takeout tradition",
"Holiday chaos|Cooking|Travel|Relatives|Gifts",
"Family photo pose|Serious|Silly|Hiding|The photographer",
"Family debate|Who is right|What to eat|What to watch|Directions",
"Video call snack|Popcorn|Coffee|Dinner|Nothing",
"You miss most|Their voice|Hugs|Their laugh|The routine",
"Your flight is canceled. You...|Rebook instantly|Panic-call someone|Find a bar|Sleep at the airport",
"You find $100 on the street. You...|Turn it in|Buy a treat|Save it|Split it with whoever is around",
"A surprise party in your honor. You...|Cry|Act shocked|Suspected it|Leave early",
"Lost in a new city with no phone|Ask a local|Follow the crowd|Walk until it looks familiar|Enjoy it",
"The elevator gets stuck. You...|Stay calm|Joke around|Press every button|Shout for help",
"Someone hands you a mic at a wedding|Give a toast|Sing|Pass it on|Vanish",
"Someone is rude to a waiter. You...|Call it out|Tip extra|Cringe silently|Change the subject",
"The power is out all night. You...|Play board games|Sleep|Light candles and eat|Doom-check the phone",
"You win a free trip, pick now|Beach|City|Wilderness|Cruise",
"Your phone dies at a party. You...|Borrow a charger|Chat with strangers|Go home|Panic",
"A group text arrives at 2am. You...|Reply|Ignore it till morning|Read and stay quiet|Turn the phone off",
"You are asked to lead a big presentation|Thrilled|Terrified|Delegate|Improvise",
"You burn dinner. You...|Order in|Scrape and eat|Start over|Blame the oven",
"Stuck in traffic|A podcast|Singing loudly|Stress|Side streets",
"A stranger compliments you|Say thanks|Deflect|Compliment back|Overthink it for a week",
"You lose a board game|Gracious|Demand a rematch|Flip the table|Say it was rigged",
"You spot a celebrity in public|Ask for a photo|Stay cool|Tell everyone|Never notice",
"Someone spoils a show you love|Silence|Fury|Forgive quickly|Watch anyway",
"A surprise free day|Adventure|Rest|Catch up on tasks|See someone",
"A friend's cooking is awful. You...|Say it is great|Be honest|Eat quickly|Bring snacks",
"What stresses them out most|Money|Work|Family|Feeling out of control",
"How they actually handle conflict|Talk it through right away|Need space first|Avoid it as long as possible|Get defensive",
"Their biggest insecurity|How they look|Their intelligence|Whether people like them|Not being enough",
"What they need most when they're upset|Advice|Someone to just listen|Space alone|A distraction",
"Their honest fear about the future|Being alone|Failing at something big|Losing someone close|Running out of time",
"Who they'd call first in a real crisis|Me|A parent|A sibling|Their best friend",
"How they really feel about their job right now|Genuinely likes it|It's fine, pays the bills|Counting down the days|Actively looking elsewhere",
"Their honest attachment style|Secure|Anxious|Avoidant|Depends on the relationship",
"What would make them walk away from a friendship|A betrayal|Being ignored|One big blowup|A slow fade, no confrontation",
"Their real love language, not the cute answer|Words of affirmation|Quality time|Physical touch|Acts of service",
"How they handle being wrong|Admit it fast|Need time to come around|Get defensive first|Rarely think they're wrong",
"Their honest take on money|Saver, plans ahead|Spender, figures it out|Stressed about it often|Doesn't think about it much",
"What they're most likely to regret not doing|Traveling more|Taking a risk on a relationship|Speaking up in a moment|Nothing, no regrets",
"How they actually recharge|Alone time, no people|Time with close friends|Doing something physical|Doing absolutely nothing",
"What they'd never admit out loud to most people|A fear|A regret|A bad habit|An opinion",
"Their honest opinion on how they were raised|Wouldn't change much|Some things they'd do differently|A lot they'd do differently|Still figuring that out",
"What actually makes them feel loved|Being chosen consistently|Being understood|Being supported publicly|Being left alone to be themselves",
"Their biggest source of pride, honestly|A relationship they built|Something they overcame|A skill or achievement|Who they've become",
"What they're most guarded about|Their past|Their feelings|Their finances|Their family"];

export const QUESTIONS = RAW.map((s) => {
  const [prompt, ...options] = s.split('|');
  return { prompt, options };
});

const CATS={'Daily life':[0,5,8,11,16,17,18,21,22,24,25,32,33,34,35,40,42,43,44,46,55,57],'Food':[6,7,15,30,38,39,45,50,56],'Travel':[1,2,4,20,26,28,29,47,58],'Romance':[3,13,19,23,31,48,49,51,52],'Chaos':[9,10,14,27,36,37,41,53,54,59],'Long distance':[60,61,62,63,64,65,66,67],'Flirty':[68,69,70,71,72,73,74,75],'Childhood':[76,77,78,79,80,81,82,83],'Family lore':[84,85,86,87,88,89,90,91],'Friends':[92,93,94,95,96,97,98,99]};
CATS['Food'].push(100,101,102,103,104);CATS['Travel'].push(105,106,107,108,109);CATS['Romance'].push(110,111,112,113,114);CATS['Chaos'].push(115,116,117,118,119);CATS['Daily life'].push(120,121,122,123,124);CATS['Childhood'].push(125,126,127);CATS['Friends'].push(128,129,130,131);CATS['Family lore'].push(132,133,134,135);CATS['Long distance'].push(136,137);CATS['Scenarios']=Array.from({length:20},(_,k)=>138+k);
CATS['Real talk']=Array.from({length:19},(_,k)=>158+k);

const AUD={Partner:['Mix it up','Scenarios','Real talk','Daily life','Food','Travel','Romance','Chaos','Childhood','Long distance','Flirty'],BFF:['Mix it up','Scenarios','Real talk','Daily life','Food','Travel','Chaos','Childhood','Friends'],Fam:['Mix it up','Scenarios','Real talk','Daily life','Food','Travel','Chaos','Childhood','Family lore']};


export const CATEGORIES = CATS;
export const AUDIENCES = AUD;

export function poolFor(audience, category) {
  if (category === 'Mix it up') {
    const excluded = new Set(['Long distance', 'Flirty'].flatMap((k) => CATS[k] || []));
    const ids = new Set();
    for (const cat of AUD[audience] || []) {
      if (cat === 'Mix it up') continue;
      for (const id of CATS[cat] || []) {
        if (!excluded.has(id)) ids.add(id);
      }
    }
    return [...ids];
  }
  return (CATS[category] || []).slice();
}
